env:
  contexts:
  - name: "Pokemon Context"
    urls:
    - "http://pokemon-php-app:80"
    includePaths:
    - "http://pokemon-php-app:80.*"
    excludePaths: []
    authentication:
      method: "form"
      parameters:
        loginPageUrl: "http://pokemon-php-app:80/signin.php"
        # Asegúrate de que esta URL es a donde apunta el <form action="..."> de tu signin.php
        # Si el form se envía a sí mismo, pon "http://pokemon-php-app:80/signin.php"
        loginRequestUrl: "http://pokemon-php-app:80/signin.php" 
        # AQUÍ ESTÁ EL CAMBIO CLAVE: usamos 'pwd' en vez de 'password'
        loginRequestBody: "email={%username%}&pwd={%password%}"
    verification:
      method: "response"
      # Algo que SOLO sale cuando NO estás logueado (ej: el botón de registrarse)
      loggedOutMatchRegex: "\\QSign up\\E"  
      # Algo que SOLO sale cuando ESTÁS logueado (ej: el botón de salir o perfil)
      loggedInMatchRegex: "\\QLog out\\E" 
    users:
    - name: "admin"
      credentials:
        username: "admin@stucom.com"
        # ¡IMPORTANTE! Pon la contraseña real que tenga este usuario en tu base de datos
        password: "password123" 
    sessionManagement:
      method: "cookie"
  parameters:
    failOnError: false
    progressToStdout: true

jobs:
- type: "spider"
  parameters:
    user: "admin"
    maxDuration: 1
- type: "passiveScan-wait"
  parameters:
    maxDuration: 0
- type: "report"
  parameters:
    template: "traditional-html"
    reportDir: "/zap/wrk"
    reportFile: "zap_report.html"
    reportTitle: "ZAP Security Report"
