env:
  contexts:
  - name: "Pokemon Context"
    urls:
    # 1. Añadimos explícitamente las páginas internas para que el Spider las vea
    - "http://pokemon-php-app"
    - "http://pokemon-php-app/main.php"
    - "http://pokemon-php-app/profile.php"
    - "http://pokemon-php-app/social.php"
    - "http://pokemon-php-app/trainerView.php"
    includePaths:
    - "http://pokemon-php-app.*"
    excludePaths:
    - "http://pokemon-php-app.*/php/logout.php"
    authentication:
      method: "form"
      parameters:
        loginPageUrl: "http://pokemon-php-app/signin.php"
        loginRequestUrl: "http://pokemon-php-app/signin.php" 
        loginRequestBody: "email={%username%}&pwd={%password%}"
      verification:
        method: "poll"
        pollUrl: "http://pokemon-php-app/main.php"
        pollFrequency: 60
        pollUnits: "requests"
        loggedOutRegex: "signin-form"
        loggedInRegex: "\\QLogout\\E"
    users:
    - name: "admin"
      credentials:
        username: "admin@stucom.com"
        password: "password123"
    sessionManagement:
      method: "cookie"
  parameters:
    failOnError: false
    progressToStdout: true

jobs:
- type: "spider"
  parameters:
    user: "admin"
    maxDuration: 2 # Aumentamos un poco el tiempo por si acaso
    parseComments: true
    handleODataParametersVisited: true
- type: "passiveScan-wait"
  parameters:
    maxDuration: 0
- type: "report"
  parameters:
    template: "traditional-html"
    reportDir: "/zap/wrk"
    reportFile: "zap_report.html"
    reportTitle: "ZAP Security Report"
