env:
  contexts:
  - name: "Pokemon Context"
    urls:
    - "http://pokemon-php-app:80"
    includePaths:
    - "http://pokemon-php-app:80.*"
    excludePaths: []
    authentication:
      method: "form"
      parameters:
        loginPageUrl: "http://pokemon-php-app:80/signin.php"
        loginRequestUrl: "http://pokemon-php-app:80/signin.php" 
        loginRequestBody: "email={%username%}&pwd={%password%}"
      verification:
        method: "response"
        loggedOutRegex: "\\QSign up\\E"
        loggedInRegex: "\\QLog out\\E"
    users:
    - name: "admin"
      credentials:
        username: "admin@stucom.com"
        password: "password123"
    sessionManagement:
      method: "cookie"
  parameters:
    failOnError: false
    progressToStdout: true

jobs:
- type: "spider"
  parameters:
    user: "admin"
    maxDuration: 1
- type: "passiveScan-wait"
  parameters:
    maxDuration: 0
- type: "report"
  parameters:
    template: "traditional-html"
    reportDir: "/zap/wrk"
    reportFile: "zap_report.html"
    reportTitle: "ZAP Security Report"
